;;; -*- Lisp -*-

(defpackage "LINEAR-FRACTIONAL-TRANSFORMATION"
  (:nicknames "LFT")
  (:shadowing-import-from "NAMED-LET" "LET")
  (:shadowing-import-from "SERIES"
                          "DEFUN"
                          "FUNCALL"
                          ;; "LET"
                          "LET*"
                          "MULTIPLE-VALUE-BIND")
  (:shadowing-import-from "STREAM" "SCAN-STREAM" "STREAM")
  (:shadow "PI")
  (:use "COMMON-LISP" "NAMED-LET" "PROMISE" "SERIES" "STREAM" "UTILITIES")
  (:export
   "->CF-STREAM"
   "2PI"
   "BIG-K-STREAM"
   "BILFT"
   "CF-STREAM"
   "COMPOSE"
   "CONS-CF-STREAM"
   "CONS-LFT-STREAM"
   "EULER-GOMPERTZ"
   "INFINITY"
   "INVERSE"
   "LFT"
   "LFT-STREAM"
   "LIMIT-STREAM->CF-STREAM"
   "MAKE-BILFT"
   "MAKE-LFT"
   "NEGATE"
   "PHI"
   "PI"
   "PI/2"
   "PYTHAGORAS"
   "RECIPROCAL"
   "SQRT-TWO"
   "SQRT-FIVE"
   "THEODORUS"
   "X*"
   "X+"
   "X-"
   "X-ACOS"
   "X-ACOSH"
   "X-ASIN"
   "X-ASINH"
   "X-ATAN"
   "X-ATANH"
   "X-CBRT"
   "X-COS"
   "X-COSH"
   "X-EXP"
   "X-EXPT"   
   "X-LOG"
   "X-SIN"
   "X-SINH"
   "X-SQRT"
   "X-SQUARE"
   "X-TAN"
   "X-TANH"
   "X/"
   ))

