;;; -*- Lisp -*-

(defpackage "LINEAR-FRACTIONAL-TRANSFORMATION"
  (:nicknames "LFT")
  (:shadowing-import-from "FUNCTION" "COMPOSE" "INVERSE")
  (:shadowing-import-from "GENERIC-ARITHMETIC"
                          "+" "-" "*" "/" "<" "<=" "=" ">" ">=" "/="
                          "1+" "1-"
                          "ABS"
                          "ACOS"
                          "ACOSH"
                          "ASIN"
                          "ASINH"
                          "ATAN"
                          "ATANH"
                          "CEILING"
                          "CIS"
                          "COMPLEX"
                          "CONJUGATE"
                          "COS"
                          "COSH"
                          "DECODE-FLOAT"
                          "DENOMINATOR"
                          "EXP"
                          "EXPT"
                          "FCEILING"
                          "FFLOOR"
                          "FLOAT"
                          "FLOAT-DIGITS"
                          "FLOAT-PRECISION"
                          "FLOAT-RADIX"
                          "FLOAT-SIGN"
                          "FLOOR"
                          "FROUND"
                          "FTRUNCATE"
                          "IMAGPART"
                          "INTEGER-DECODE-FLOAT"
                          "LOG"
                          "MAX" 
                          "MIN" 
                          "MOD" 
                          "NUMERATOR" 
                          "PHASE" 
                          "RANDOM" 
                          "RATIONAL" 
                          "RATIONALIZE" 
                          "REALPART"
                          "RECIPROCAL"
                          "REM" 
                          "ROUND" 
                          "SCALE-FLOAT" 
                          "SIGNUM"
                          "SIN"
                          "SINH"
                          "SQRT"
                          "TAN"
                          "TANH"
                          "TRUNCATE"
                          "ZEROP")
  (:shadowing-import-from "NAMED-LET" "LET")
  (:shadowing-import-from "SERIES"
                          "DEFUN"
                          "FUNCALL"
                          ;; "LET"
                          "LET*"
                          "MULTIPLE-VALUE-BIND")
  (:shadowing-import-from "STREAM" "SCAN-STREAM" "STREAM")
  (:shadow "PI")
  (:use "COMMON-LISP" "FOLD" "FUNCTION" "GENERIC-ARITHMETIC" "NAMED-LET" "PROMISE" "SERIES" "STREAM" "UTILITIES")
  (:export
   "->CF-STREAM"
   "2PI"
   "BIG-K-STREAM"
   "BILFT"
   "CF-STREAM"
   "CONS-CF-STREAM"
   "CONS-LFT-STREAM"
   "EULER-GOMPERTZ"
   "INFINITY"
   "LFT"
   "LFT-STREAM"
   "LIMIT-STREAM->CF-STREAM"
   "MAKE-BILFT"
   "MAKE-LFT"
   "PHI"
   "PI"
   "PI/2"
   "PYTHAGORAS"
   "SQRT-TWO"
   "SQRT-FIVE"
   "THEODORUS"
   ))

